### ISSUE TITLE
The wallet is not reflecting the right balance on the polkadot network

### ISSUE THREAD

**Issue by vicoysito** [ChainSafe/metamask-snap-polkadot#206]
Log: 

sendSnapMethod 
{method: 'getBalance'}
method
: 
"getBalance"

RPC Error: The snap "npm:@chainsafe/polkadot-snap" has been terminated during execution. {code: -32603, message: 'The snap "npm:@chainsafe/polkadot-snap" has been terminated during execution.'.

---
MetaMask - RPC Error: The request timed out. 

{
    "code": -32603,
    "message": "The request timed out.",
    "data": {
        "originalError": {}
    }
}

**Comment by vicoysito** [comment]
I was able to replicate the error: 
If you change the network and select Kusama or Polkadot the is being closed

![image](https://github.com/ChainSafe/metamask-snap-polkadot/assets/1297131/02c8252b-bf89-49b5-b2b9-599537e2004d)

**Comment by BeroBurny** [comment]
Thanks for reaching out and reporting an issue.

One of the team members will jump in quickly and try to resolve the issue quickly.

**Comment by vicoysito** [comment]
is there a way to export the seeds of the Polkadot Wallet that was created when install the snap on Metamask?, I tried using the Metamask seeds phrase on Polkadot-js but unfortunately the address is not the same and the balance is 0 on that wallet.

**Comment by vicoysito** [comment]
Hi Guys, not sure if this issue is related with this other one: https://github.com/ChainSafe/metamask-snap-polkadot/issues/204. They report that it's impossible to use the Polkadot and Kusama network.

**Comment by Lykhoyda** [comment]
Hi @vicoysito ! I'm sorry for the delay in response and thank you for your patience! I tried to replicate the error by switching the networks and got no error so far. I'm using the Brave browser, but it should work regardless of it. The error could occur due to too many getBalance requests, so some might get timed out, but you still should see the correct balance. In the screenshot that you provided, there is a get balance call before the error which was successful.  

For example, I tested the scenario on the Westend network to receive some tokens from the faucet and it showed me the correct value. https://westend.subscan.io/account/5GkEEbixbNo3xTymj5y13uKtgamR2RwAjiL3EKXMSzNCJnCV
<img width="1336" alt="Screenshot 2023-11-10 at 12 14 06" src="https://github.com/ChainSafe/metamask-snap-polkadot/assets/8141917/0320e739-1b2a-46d7-aff4-4a22c89012b3">

If you think that the balance displayed in the App is not correct, can you please share the Address, to find the correct value on subscan.

**Comment by vicoysito** [comment]
Thanks for your Response @Lykhoyda, Westend network worked fine but when I try to transfer my dots using the Polkadot network or join to a pool is when the timeout error happened. I've tried using Brave and same timeout error. So if you have an example of how I can transfer my dots to another wallet or how use this snap wallet to transfer my dots to another wallet I will really appreciate it. 

https://polkadot.subscan.io/account/1r6Ybk4pUZBiPbwcQaNEMAWMiS2EZwRED3YBqTrrct9Bpgm

![Polkadot_error](https://github.com/ChainSafe/metamask-snap-polkadot/assets/1297131/234833b3-4764-4c5b-aa7e-70adcea38452)

**Comment by Lykhoyda** [comment]
@vicoysito we released the fix for the transfer issue, you should be able to transfer the tokens

**Comment by BeroBurny** [comment]
Pipeline failed  :cry:, will be fixed today released
